- hosts: all
  become: true
  tasks:
    - name: create new deployment named westeros
      command: kubectl create -f /home/ubuntu/k8s/deployment.yaml
      become: yes
      become_user: ubuntu
    - name: create new svc named kingslanding
      command: kubectl create -f /home/ubuntu/k8s/svc.yaml
      become: yes
      become_user: ubuntu

