apiVersion: v1
kind: Service
metadata:
  name: kingslanding
  labels:
    app: lanister
spec:
  type: LoadBalancer
  selector:
    app: lanister
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200

